# Generated by Django 2.2.17 on 2023-07-17 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_test', '0004_testsuit'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSuitTestCases',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(default=1, verbose_name='是否有效')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_test.TestCase', verbose_name='测试用例')),
                ('test_suit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_test.TestSuit', verbose_name='测试集合')),
            ],
        ),
    ]
